# Nombre de la aplicación
spring.application.name=servicio-gateway

# Configuración del servidor
server.port=9000

# Configuración de Eureka
eureka.client.register-with-eureka=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Configuración del Gateway
#spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE

# Configuración CORS
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedOrigins=http://localhost:8080
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedHeaders=*

# Rutas para los microservicios
spring.cloud.gateway.routes[0].id=servHotel
spring.cloud.gateway.routes[0].uri=lb://SERVICIO-HOTEL
spring.cloud.gateway.routes[0].predicates[0]=Path=/shotel/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/shotel/(?<segment>.*), /$\{segment}

spring.cloud.gateway.routes[1].id=servvuelos
spring.cloud.gateway.routes[1].uri=lb://SERVICIO-VUELOS
spring.cloud.gateway.routes[1].predicates[0]=Path=/svuelos/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/svuelos/(?<segment>.*), /$\{segment}

spring.cloud.gateway.routes[2].id=serreservas
spring.cloud.gateway.routes[2].uri=lb://SERVICIO-RESERVAS
spring.cloud.gateway.routes[2].predicates[0]=Path=/sreservas/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/sreservas/(?<segment>.*), /$\{segment}






